source 'https://rubygems.org'
gem 'sequel'
gem 'sinatra', :require => "sinatra/synchrony"
gem 'sinatra-synchrony'
#gem 'pg'
gem 'rack'
gem 'rchardet19'
gem 'sanitize'
gem 'htmlcompressor'
gem 'thin'
gem 'erubis'
gem 'eventmachine'
gem 'em-pg-client'
gem 'nokogiri'
gem 'pry'
gem 'bb-ruby'
gem 'dalli'
gem 'msgpack'
gem 'sequel-query-cache', :git => 'https://github.com/binarypaladin/sequel-query-cache'
